### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by wboerhout** [kgober/VT52#4]
Is there a way to save the F5 and F6 settings and start the emulator with the saved settings?
From the code, I see I can start with `VT52 -t host:port,` but for my VMS V1.0 project on simh I need a raw connection, and preferably green text.

**Comment by kgober** [comment]
There is no way to do this in v1.0.0.3.  A more general and full-featured way is planned for "someday" but in the meantime I will add something basic in v1.0.0.4 for this.

**Comment by kgober** [comment]
OK, v1.0.0.4 is available and should do what you need.  `VT52 -r host:port -og+` to connect using raw tcp, with the green text option turned on.

**Comment by wboerhout** [comment]
Excellent!
Op vr 1 dec. 2017 om 03:40 schreef kgober <notifications@github.com>
