### ISSUE TITLE
case 'Y': // ESC Y - Direct Cursor Addressing

### ISSUE THREAD

**Issue by matthewgeier** [kgober/VT52#5]
Direct cursor addressing does not currently appear to be supported.  Any chance of this being added ?
I've had to connect to an embedded device for diagnostics and discovered the vendor of this device back in the day decided to use VT52 terminal instead of ANSI.
The diagnostic console constantly updates a status bar in the middle of the display. The numbers just end up overwriting the menu. We managed to get up one test screen where it updates 8 values in real-time. We got a screen with descriptions and XXX.X then a jumble of changing numbers in the top corner.
The device came with a DOS program to interact with it, but it won't run under any emulation, seems the original program wants to talk to a real UART chip directly. Thanks.

**Comment by kgober** [comment]
It does support ESC Y actually, but it's unclear to me why it's not working for you.  I play rogue on an old Unix system using this emulator quite often, which uses ESC Y a great deal.  I suspect that the DOS program that came with your device implements some other emulation (or is buggy), and that your embedded device is set up to work with that particular emulation.

I'm interested in tracking down the problem regardless.  Do you have the ability to compile VT52 in Debug mode?  That will enable logging of all input VT52 receives, so we can confirm what VT52 is actually receiving.

**Comment by kgober** [comment]
If it helps, I've recompiled v1.0.0.9 with DEBUG enabled.  It's not a "release" so you'll need to download the files directly from the bin folder (https://github.com/kgober/VT52/tree/master/bin).  You can use a tool like Microsoft SysInternals DebugView (https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) to view/save the debug output.  To make it easy to filter out debug messages from other programs running on your system, all VT52 messages are prefixed "VT52: " so you can use that as a filter.

**Comment by kgober** [comment]
I'm going to close this as an issue, but please feel free to send me a log capture from DebugView and I'll see if I can help you resolve your issue, or at least point you in the right direction to a solution.

**Comment by matthewgeier** [comment]
Did you get the capture I made last week or did that email manage to get eaten due to the attachments ?

I looked at the debug. I think my problem is is the device is using GEMDOS not 'pure' VT52.  (Looking at Wikipedia VT52 page)

So things are being written in the wrong place because the ESC E command isn't being acted on. It sends an ESC E and expects to be drawing on a new clear screen from the top.

I spotted Reverse video (ESC p) and Normal Video (ESC q) as well, but lack of those shouldn't stop the screen from being readable.

**Comment by kgober** [comment]
I didn't get it, sorry.  Yes, ESC E would certainly explain why things aren't working.  Do you believe that ESC E is currently the only thing preventing VT52 from working for you?  It wouldn't be hard to add, although I'd have to figure out how to manage it (fork VT52 entirely, or just make it a branch for this, or add it to trunk with a command line option to enable, etc.)
